### ISSUE TITLE
Sample code in Readme not working PolicyRegistry()

### ISSUE THREAD

**Issue by javaadpatel** [App-vNext/Polly.Caching.IDistributedCache#18]
Hi,

The sample dotnetcore code:
```
PolicyRegistry registry = new PolicyRegistry();
```
gives the error "PolicyRegistry does not contain a constructor that contains 0 arguments"

**Comment by reisenberger** [comment]
Which version of `Polly` does your code reference?  There was a bug in Polly v7.0.1-v7.0.3 which caused this, [fixed in v7.1.0](https://github.com/App-vNext/Polly/blob/master/CHANGELOG.md#710), around March 2019.  The latest code (Polly v7.1.0) [certainly has that constructor](https://github.com/App-vNext/Polly/blob/eff944e005ba3e39c22f4f00e60b07baf57165ec/src/Polly/Registry/PolicyRegistry.cs#L20-L26)

Let me know if this resolves the issue for you.

**Comment by reisenberger** [comment]
We should fix the Polly version references in this repo to reference Polly v7.1.0:

+ [in the nuspec](https://github.com/App-vNext/Polly.Caching.IDistributedCache/blob/86183466c1aa064ce757dba991fc82de13e26ce1/src/Polly.Caching.Distributed.nuspec#L40-L50) 
+ in all four .csproj files

(and then re-release as v3.0.1)

**Comment by javaadpatel** [comment]
Thank you for the help, the issue was that I did not have Polly installed. I pulled in the Polly.Caching.Distributed package and this made the PolicyRegistry type available but it was not the one that's in the core Polly package.

**Comment by reisenberger** [comment]
@javaadpatel There is [no PolicyRegistry type in the `Polly.Caching.Distributed` package](https://github.com/App-vNext/Polly.Caching.IDistributedCache/search?q=PolicyRegistry&unscoped_q=PolicyRegistry) but the nuget package does have a [dependency on Polly](https://github.com/App-vNext/Polly.Caching.IDistributedCache/blob/86183466c1aa064ce757dba991fc82de13e26ce1/src/Polly.Caching.Distributed.nuspec#L40-L50), so installing `Polly.Caching.Distributed` in your project would have _indirectly_ installed a version of Polly (probably 7.0.1, still having the `PolicyRegistry` constructor error).  If using Visual Studio, you can see this if you expand the Dependencies -> nuget nodes of your solution.

![image](https://user-images.githubusercontent.com/9608723/61319753-c54a7100-a7ff-11e9-800e-5067cfff8e5f.png)

If you then installed Polly v7.1.0 as a top-level (direct) dependency of your project, that would indeed fix the issue, because the project will reference v7.1.0 in both places (both directly and indirectly).

![image](https://user-images.githubusercontent.com/9608723/61319989-5e798780-a800-11e9-9ec7-bdf6bfa6284b.png)

**Comment by javaadpatel** [comment]
That's quite interesting, because i also thought it would have pulled the core Polly package in but when i checked the nuget package manager Polly was not installed only Polly.Distributed.Cache

**Comment by reisenberger** [comment]
It looks like, when the package is installed only _indirectly_, it doesn't show it in the package manager dialog (good to know - thank you for pointing that out).  

![image](https://user-images.githubusercontent.com/9608723/61320536-7d2c4e00-a801-11e9-9a24-30fec7107395.png)

**Comment by javaadpatel** [comment]
I most likely pulled the package in using the Quick Actions (CTRL+.), so that could be the cause.
